######################################################################
# Automatically generated by qmake (2.01a) Fri May 8 15:41:54 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += ../../src

# Input
SOURCES += main.cpp ../../src/qtsegmentcontrol.cpp
HEADERS += ../../src/qtsegmentcontrol.h

